[[main]]
  name = "About"
  url = "/about/"
  weight = 20

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20
  
[[main]]
  name = "Library"
  url = "/library/"
  weight = 20



# [[about]]
#     name = "About"
#     weight = 10
#     identifier = "about"
#     url = "/about/info/workstreams.md"



# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
