[[main]]
  name = "PROTOTYPE"
  url = "/prototype/"
  weight = 10

[[main]]
  name = "About"
  url = "/about/"
  weight = 20

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 30

[[main]]
    name = "Weeknotes"
    url = "/weeknotes/"
    weight = 40

[[about]]
    name = "Prologue"
    weight = 10
    identifier = "prologue"
    url = "/about/prologue/"

[[about]]
    name = "Help"
    weight = 60
    identifier = "help"
    url = "/about/help/"


# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
